### ISSUE TITLE
Error in file migration

### ISSUE THREAD

**Issue by kriptograf** [nanson/yii2-messenger#2]
Hello. You have to migrate the error occurred. Previously, it was not.
Before migration inherited from class `\yii\db\Migration`
And now it inherited from 
`class m151214_135143_create_massages_table extends \app\modules\main\db\Migration`
But in the code there is no such namespace. And there is no such class. Because of this error when migration.

**Comment by thedenische** [comment]
Thanks.
I tested it with [rzwebsys7](https://github.com/webadmin87/rzwebsys7) cms. This namespace from there.
