### ISSUE TITLE
Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

### ISSUE THREAD

**Issue by SuperBilge** [nanson/yii2-messenger#3]
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `user`.*, max(`nanson_messenger_messages`.`id`) AS `last_message_id` FROM `user` INNER JOIN `nanson_messenger_messages` ON (`user`.`id` = `nanson_messenger_messages`.`author_id`) OR (`user`.`id` = `nanson_messenger_messages`.`recipient_id`) WHERE ((`author_id`=2) OR (`recipient_id`=2)) AND (`id` != 2) GROUP BY `id`) `c`

 AND (`id` != 2) -> must be `user`.`id`
this error occured on /messenger/contacts and adding Contacts::widget on page
some fixes or my User model have errors?

**Comment by thedenische** [comment]
Could you show me full stack trace?

**Comment by SuperBilge** [comment]
> Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous The SQL being executed was: SELECT COUNT(*) FROM (SELECT `user`.*, max(`nanson_messenger_messages`.`id`) AS `last_message_id` FROM `user` INNER JOIN `nanson_messenger_messages` ON (`user`.`id` = `nanson_messenger_messages`.`author_id`) OR (`user`.`id` = `nanson_messenger_messages`.`recipient_id`) WHERE ((`author_id`=2) OR (`recipient_id`=2)) AND (`id` != 2) GROUP BY `id`) `c` in C:\xampp\htdocs\network\vendor\yiisoft\yii2\db\Schema.php:636 Stack trace: #0 C:\xampp\htdocs\network\vendor\yiisoft\yii2\db\Command.php(930): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...') 
#1 C:\xampp\htdocs\network\vendor\yiisoft\yii2\db\Command.php(388): yii\db\Command->queryInternal('fetchColumn', 0) 
#2 C:\xampp\htdocs\network\vendor\yiisoft\yii2\db\Query.php(438): yii\db\Command->queryScalar() 
#3 C:\xampp\htdocs\network\vendor\yiisoft\yii2\db\ActiveQuery.php(339): yii\db\Query->queryScalar('COUNT(*)', Object(yii\db\Connection)) 
#4 C:\xampp\htdocs\network\vendor\yiisoft\yii2\db\Query.php(319): yii\db\ActiveQuery->queryScalar('COUNT(*)', Object(yii\db\Connection)) 
#5 C:\xampp\htdocs\network\vendor\yiisoft\yii2\data\ActiveDataProvider.php(169): yii\db\Query->count('*', NULL) 
#6 C:\xampp\htdocs\network\vendor\yiisoft\yii2\data\BaseDataProvider.php(169): yii\data\ActiveDataProvider->prepareTotalCount() 
#7 C:\xampp\htdocs\network\vendor\yiisoft\yii2\data\ActiveDataProvider.php(106): yii\data\BaseDataProvider->getTotalCount() 
#8 C:\xampp\htdocs\network\vendor\yiisoft\yii2\data\BaseDataProvider.php(101): yii\data\ActiveDataProvider->prepareModels() 
#9 C:\xampp\htdocs\network\vendor\yiisoft\yii2\data\BaseDataProvider.php(114): yii\data\BaseDataProvider->prepare()
 #10 C:\xampp\htdocs\network\vendor\yiisoft\yii2\data\BaseDataProvider.php(155): yii\data\BaseDataProvider->getModels()
 #11 C:\xampp\htdocs\network\vendor\yiisoft\yii2\widgets\BaseListView.php(189): yii\data\BaseDataProvider->getCount() 
#12 C:\xampp\htdocs\network\vendor\yiisoft\yii2\widgets\BaseListView.php(157): yii\widgets\BaseListView->renderSummary() 
#13 C:\xampp\htdocs\network\vendor\yiisoft\yii2\grid\GridView.php(316): yii\widgets\BaseListView->renderSection('{summary}') 
#14 C:\xampp\htdocs\network\vendor\yiisoft\yii2\widgets\BaseListView.php(134): yii\grid\GridView->renderSection('{summary}') 
#15 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array) 
#16 C:\xampp\htdocs\network\vendor\yiisoft\yii2\widgets\BaseListView.php(137): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...') 
#17 C:\xampp\htdocs\network\vendor\yiisoft\yii2\grid\GridView.php(291): yii\widgets\BaseListView->run() 
#18 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\Widget.php(139): yii\grid\GridView->run() 
#19 C:\xampp\htdocs\network\vendor\nanson\yii2-messenger\widgets\views\contacts.php(38): yii\base\Widget::widget(Array) 
#20 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\View.php(330): require('C:\\xampp\\htdocs...') 
#21 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('C:\\xampp\\htdocs...', '[<span class="s...') 
#22 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\View.php(152): yii\base\View->renderFile('C:\\xampp\\htdocs...', Array, Object(nanson\messenger\widgets\Contacts)) 
#23 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\Widget.php(234): yii\base\View->render('contacts', Array, Object(nanson\messenger\widgets\Contacts)) 
#24 C:\xampp\htdocs\network\vendor\nanson\yii2-messenger\widgets\Contacts.php(103): yii\base\Widget->render('contacts', Array) 
#25 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\Widget.php(139): nanson\messenger\widgets\Contacts->run() 
#26 C:\xampp\htdocs\network\vendor\nanson\yii2-messenger\views\contacts\index.php(10): yii\base\Widget::widget() 
#27 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\View.php(330): require('C:\\xampp\\htdocs...') 
#28 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('C:\\xampp\\htdocs...', '[]') 
#29 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\View.php(152): yii\base\View->renderFile('C:\\xampp\\htdocs...', Array, Object(nanson\messenger\controllers\ContactsController)) 
#30 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\Controller.php(381): yii\base\View->render('index', Array, Object(nanson\messenger\controllers\ContactsController)) 
#31 C:\xampp\htdocs\network\vendor\nanson\yii2-messenger\controllers\ContactsController.php(37): yii\base\Controller->render('index') 
#32 [internal function]: nanson\messenger\controllers\ContactsController->actionIndex() 
#33 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array) 
#34 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array) 
#35 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('', Array) 
#36 C:\xampp\htdocs\network\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('messenger/conta...', Array) 
#37 C:\xampp\htdocs\network\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request)) 
#38 C:\xampp\htdocs\network\mobile\web\index.php(17): yii\base\Application->run() 
#39 {main} Additional Information: Array ( [0] => 23000 [1] => 1052 [2] => Column 'id' in where clause is ambiguous )

**Comment by thedenische** [comment]
Are you override  \yii\db\ActiveRecord::tableName method in your model?
Show me this method, if it has been overridden.

**Comment by SuperBilge** [comment]
public static function tableName()
    {
        return 'user';
    }

**Comment by thedenische** [comment]
Which yii2 and php version you are using?

**Comment by SuperBilge** [comment]
yii 2.0.12
composer.json: "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.6",
на сервере php 7.1.4

**Comment by thedenische** [comment]
I was using this module with Yii 2.0.5, and it worked correctly.
I got the same query after updating up to Yii 2.0.12

**Comment by thedenische** [comment]
Try to update module

**Comment by SuperBilge** [comment]
спасибо, заработало. только в своей модели я убрал поле username, поэтому начало снова ругаться. но это уже другая история.

**Comment by thedenische** [comment]
Это решается переопределением view для виджетов. В модуле они совсем простые, на базе стандартных виджетов, для демонстрации.
А так - у всех свои модели пользователей (со своими полями), у всех свои дизайны и т.д.
